name: Update Action major tag

on:
  release:
    types: [published, edited]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Repoint the major tag
        run: |
          export TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          export MAJOR=${TAG%%.*}
          git config user.name 'Github Actions'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git tag --force -a "${MAJOR}" -m "release: ${MAJOR}"
          git push --force origin "${MAJOR}"